spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_post_last
    username: root
    password: Iopjkl@890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.MySQLDialect
    
    
server:
  port: 7091    
  
  
  
app:
  message:
    resMsg: Registration Successfull
    emailExist: Email is Already Resistered...
      